# hosts/tuvalu/hardware.nix
# Generated by nixos-generate-config at install time — replace placeholder with real output. Also imports nixos-hardware ThinkPad module (AI-035: verify exact module name)
# PLACEHOLDER — implement in Phase 1 / Phase 2 as noted
{ ... }:
{
}
